export enum EnumDeliveryEventType {
  CREATED = 'CREATED',
  CONFIRMED = 'CONFIRMED',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  DISPATCHED = 'DISPATCHED',
  CANCELED = 'CANCELED',
  FULFILLED = 'FULFILLED',
  ARRIVED_AT_DROPOFF_LOCATION = 'ARRIVED_AT_DROPOFF_LOCATION',
  DROPPED_OFF = 'DROPPED_OFF',
  ARRIVED_AT_PICKUP_LOCATION = 'ARRIVED_AT_PICKUP_LOCATION',
  PICKED_UP = 'PICKED_UP',
  ON_THE_WAY = 'ON_THE_WAY',
  FAILED = 'FAILED',
}

export enum NotificationEventType {
  DELIVERY_STATUS_UPDATED = 'DELIVERY_STATUS_UPDATED',
}
